# Generated by Django 3.0.3 on 2020-07-08 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('age_group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('age_group_desc', models.CharField(blank=True, max_length=20, null=True)),
                ('age_group_start', models.DateField(blank=True, null=True)),
                ('age_group_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'age_group',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('coach_id', models.IntegerField(primary_key=True, serialize=False)),
                ('coach_first', models.CharField(blank=True, max_length=20, null=True)),
                ('coach_last', models.CharField(blank=True, max_length=20, null=True)),
                ('coach_phone', models.IntegerField(blank=True, null=True)),
                ('coach_email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'coach',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('contact_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contact_first', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_last', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'emergency_contact',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_id', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_first', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_last', models.CharField(blank=True, max_length=20, null=True)),
                ('manager_phone', models.IntegerField(blank=True, null=True)),
                ('manager_email', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.EmergencyContact')),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='BattingStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sluggers.Player')),
                ('plate_appearances', models.IntegerField(blank=True, null=True)),
                ('at_bats', models.IntegerField(blank=True, null=True)),
                ('sacrifices', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
                ('rbi', models.IntegerField(blank=True, null=True)),
                ('home_runs', models.IntegerField(blank=True, null=True)),
                ('singles', models.IntegerField(blank=True, null=True)),
                ('doubles', models.IntegerField(blank=True, null=True)),
                ('triples', models.IntegerField(blank=True, null=True)),
                ('steals', models.IntegerField(blank=True, null=True)),
                ('walks', models.IntegerField(blank=True, null=True)),
                ('hit_by_pitch', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batting_stats',
            },
        ),
        migrations.CreateModel(
            name='FieldingStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sluggers.Player')),
                ('errors', models.IntegerField(blank=True, null=True)),
                ('putouts', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('total_chances', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fielding_stats',
            },
        ),
        migrations.CreateModel(
            name='PitchingStats',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sluggers.Player')),
                ('hits_allowed', models.IntegerField(blank=True, null=True)),
                ('runs_allowed', models.IntegerField(blank=True, null=True)),
                ('earned_runs_allowed', models.IntegerField(blank=True, null=True)),
                ('innings_thrown', models.IntegerField(blank=True, null=True)),
                ('pitches_thrown', models.IntegerField(blank=True, null=True)),
                ('strikes_thrown', models.IntegerField(blank=True, null=True)),
                ('strike_outs', models.IntegerField(blank=True, null=True)),
                ('walks', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pitching_stats',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=30, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.IntegerField(blank=True, null=True)),
                ('age_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.AgeGroup')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Coach')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Manager')),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Team'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='sluggers.Team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='sluggers.Team')),
            ],
            options={
                'db_table': 'match',
            },
        ),
        migrations.CreateModel(
            name='Inning',
            fields=[
                ('inning_num', models.IntegerField(primary_key=True, serialize=False)),
                ('home_hits', models.IntegerField(blank=True, null=True)),
                ('home_runs', models.IntegerField(blank=True, null=True)),
                ('home_errors', models.IntegerField(blank=True, null=True)),
                ('away_hits', models.IntegerField(blank=True, null=True)),
                ('away_runs', models.IntegerField(blank=True, null=True)),
                ('away_errors', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Match')),
            ],
            options={
                'db_table': 'inning',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='sluggers.Manager')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sluggers.Team')),
            ],
            options={
                'db_table': 'staff',
                'unique_together': {('manager', 'coach', 'team')},
            },
        ),
    ]
