# Generated by Django 3.0.3 on 2020-07-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sluggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agegroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='battingstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fieldingstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='inning',
            options={},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pitchingstats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={},
        ),
    ]
