# Generated by Django 3.0.3 on 2020-07-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sluggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inning',
            options={'ordering': ['match', 'inning_num']},
        ),
        migrations.AlterUniqueTogether(
            name='inning',
            unique_together={('match', 'inning_num')},
        ),
    ]
